FROM nginx:alpine

# Copia todos os arquivos estáticos do frontend para o diretório de destino do Nginx
COPY . /usr/share/nginx/html

# Copia o arquivo de configuração customizado do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expõe a porta 80 que o Nginx escuta
EXPOSE 80
