FROM node:20-alpine

# Cria diretório da aplicação
WORKDIR /usr/src/app

# Copia dependências (package.json e package-lock.json se existir)
COPY package*.json ./

# Instala apenas dependências de produção
RUN npm ci --only=production

# Copia o restante do código backend
COPY . .

# Expõe a porta 3000
EXPOSE 3000

# Inicia a aplicação
CMD ["node", "src/server.js"]
